version: '3.8'

services:
  proxy:
    build:
      context: ./
      dockerfile: cmd/proxy/Dockerfile
    command: ./sec-proxy
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  app:
    build:
      context: ./
      dockerfile: cmd/app/Dockerfile
    command: ./sec-app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db:rw